### ISSUE TITLE
[Bug] Schedule returns undefined value

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackportal#191]
### What did you expect to happen?

Empty/unpopulated schedule should show up

### What happened?

The schedule currently returns undefined if number of events = 0

### Scope

Events

**Comment by Spaceface16518** [comment]
So I narrowed this down to the grouping child components of `Scheduler`. It doesn't know how to render groups because groups are computed from appointments. Is there some way the component can get a list of possible tracks ahead of time? Or is the only way to get them to compute the from given appointments.

If I wanted to improve the schedule component overall, I would do 2 things differently.

1. Return only relevant events based on date range; the current implementation queries all events in every API call.
2. Return the tracks computed from all events separately from the appointments, so that groupings can be shown regardless of events.

This would not mitigate the issue at hand, but it would be an better implementation overall, I think.
